name: "AIS Ship Tracker"
version: "1.4.8"
slug: "ais_ship_tracker"
description: "Tracks passing ships via AISStream"
url: "https://github.com/pschmitt/ais_ship_tracker"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
startup: "services"
boot: "auto"
icon: "icon.png"
init: false
homeassistant_api: true
options:
  api_key: ""
  longitude_west: 1.20
  latitude_south: 50.90
  longitude_east: 1.80
  latitude_north: 51.20
  enable_map_entities: false
  include_class_b: true
  vessel_watchlist: ""
  clear_map_on_startup: false
  map_timeout_minutes: 30
  enable_api_monitoring: true
schema:
  api_key: "password"
  longitude_west: "float"
  latitude_south: "float"
  longitude_east: "float"
  latitude_north: "float"
  enable_map_entities: "bool?"
  include_class_b: "bool?"
  vessel_watchlist: "str?"
  clear_map_on_startup: "bool?"
  map_timeout_minutes: "int?"
  enable_api_monitoring: "bool?"
